<footer id="site-footer" class="site-footer">
  <div class="site-container">

    <div class="left-part">
      <span>© 2015  Fried · Kilpatrick · Guinn</span>
      <ul>
        <li>
          <a href="#">Privacy Statement</a>
        </li>
        <li>
          <a href="#">Terms of Use</a>
        </li>
      </ul>
    </div>

    <nav class="nav">
      <ul class="menu">
        <li><a href="#"> Home</a></li>
        <li><a href="#">Clients</a></li>
        <li><a href="#">FKG Reports</a></li>
        <li><a href="#">Contact Us</a></li>
      </ul>
    </nav>
  </div>
</footer>