<header id="site-header" class="site-header">
  <div class="site-container">
    <div class="logo">
      <a href="#">
        <img src="theme/images/logo.png" alt="">
      </a>
    </div>

    <nav class="nav">
      <ul class="menu">
        <li class="active"><a href="#">Home</a> </li>
        <li><a href="#">Clients</a> </li>
        <li><a href="#">Blog</a> </li>
        <li><a href="#">Contact Us</a> </li>
      </ul>
    </nav>
    <a href="#" class="mobile-menu"><span></span></a>
  </div>
</header>